name: Kirim DM Massal

on:
  workflow_dispatch:

jobs:
  send-dm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install discord.py
        run: pip install discord.py
      - name: Jalankan Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python main.py
